// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPmqptVMRWKWnV8f5SVwpCG-ZhRuvdxiU',
    appId: '1:201003618205:web:faee085fe032845639a974',
    messagingSenderId: '201003618205',
    projectId: 'sih-app-72aa3',
    authDomain: 'sih-app-72aa3.firebaseapp.com',
    storageBucket: 'sih-app-72aa3.appspot.com',
    measurementId: 'G-BPMG3PH0N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAioFmMOa5vXkVHCIMkZh71YI_23N7wms0',
    appId: '1:201003618205:android:f55cd9bda21bdf8739a974',
    messagingSenderId: '201003618205',
    projectId: 'sih-app-72aa3',
    storageBucket: 'sih-app-72aa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEWbAsM-xOgrbKl2uRmdEfvbeFZMRi5aE',
    appId: '1:201003618205:ios:22ff30db4b6ecdad39a974',
    messagingSenderId: '201003618205',
    projectId: 'sih-app-72aa3',
    storageBucket: 'sih-app-72aa3.appspot.com',
    iosClientId:
        '201003618205-ra96l1l8c2og82i8ao1sm39gq5uu2de4.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.quizzle',
  );
}
